#!/bin/python
import pyautogui as auto
import os
import sys

input1 = sys.argv[1]
dict1 = {}

# (width, height)
# (0, 1)
def midpoint(dimension):
    return auto.size()[dimension]/2

# i3 directions
dict1["h"] = [-1, midpoint(1)]
dict1["j"] = [midpoint(0), 10000]
dict1["k"] = [960, -1]
dict1["l"] = [10000, midpoint(1)]

auto.moveTo(dict1[input1])